schedules:
- cron: "0 0 * * Sun,Thu"
  displayName: At 00:00 on Sunday and Thursday.
  branches:
    include:
    - master

parameters:
  - name: 'SUBSCRIPTION_SERVICE_CONNECTION'
    displayName: 'Azure subscription service connection name hosting the infrastructure built with terraform'
    type: string
    default: PROD-IO-SERVICE-CONN
    values:
      - PROD-IO-SERVICE-CONN
      - DEV-IO-SERVICE-CONN
  - name: 'SUBSCRIPTION_NAME'
    displayName: 'Azure subscription name hosting the infrastructure built with terraform'
    type: string
    default: PROD-IO
    values:
      - PROD-IO
      - DEV-IO
  - name: 'KEYVAULT_NAME'
    displayName: 'The key vault instance we want to backup.'
    type: string
    default: io-p-kv-common
  - name: 'STORAGE_ACCOUNT_NAME'
    displayName: 'Storage account where to save.'
    type: string
    default: iopstbackups
  - name: 'CONTAINER_NAME'
    displayName: 'Name of the container inside the storage account'
    type: string
    default: kv-secrets

pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: backup_secrets
    steps:
      # 1. Run bash script based on az cli
      - task: AzureCLI@2
        env:
          GIT_BRANCH: $(Build.SourceBranchName)
        displayName: Run backup secrets
        inputs:
          azureSubscription: '${{ parameters.SUBSCRIPTION_SERVICE_CONNECTION }}'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: '.devops/backup-secrets.sh'
          failOnStandardError: false
          arguments:
            ${{ parameters.SUBSCRIPTION_NAME }}
            ${{ parameters.KEYVAULT_NAME }}
            ${{ parameters.STORAGE_ACCOUNT_NAME }}
            ${{ parameters.CONTAINER_NAME }}
